enum ErrorCodes {
  /** 500 */
  INTERNAL = "INTERNAL_SERVER_ERROR",
  /** 401 */
  MISSING_TOKEN = "MISSING_TOKEN",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_HAS_EXPIRED = "TOKEN_HAS_EXPIRED",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  /** 404 */
  USER_NOT_FOUND = "USER_NOT_FOUND",
  /** 400 */
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  NAME_MUST_BE_TEXT = "NAME_MUST_BE_TEXT",
  NAME_EXCEEDS_LENGTH_80 = "NAME_EXCEEDS_LENGTH_80",
  NAME_IS_REQUIRED = "NAME_IS_REQUIRED",
  RESPONSIBLE_IS_REQUIRED = "RESPONSIBLE_IS_REQUIRED",
  RESPONSIBLE_MUST_BE_TEXT = "RESPONSIBLE_MUST_BE_TEXT",
  RESPONSIBLE_EXCEEDS_LENGTH_100 = "RESPONSIBLE_EXCEEDS_LENGTH_100",
  NAME_EXCEEDS_LENGTH_100 = "NAME_EXCEEDS_LENGTH_100",
  EMAIL_MUST_BE_TEXT = "EMAIL_MUST_BE_TEXT",
  EMAIL_IS_INVALID = "EMAIL_IS_INVALID",
  EMAIL_IS_REQUIRED = "EMAIL_IS_REQUIRED",
  PASSWORD_MUST_BE_TEXT = "PASSWORD_MUST_BE_TEXT",
  PASSWORD_IS_REQUIRED = "PASSWORD_IS_REQUIRED",
  PASSWORD_IS_INVALID = "PASSWORD_IS_INVALID",
  PHONE_MUST_BE_TEXT = "PHONE_MUST_BE_TEXT",
  PHONE_EXCEEDS_LENGTH_40 = "PHONE_EXCEEDS_LENGTH_40",
  ROLE_IS_REQUIRED = "ROLE_IS_REQUIRED",
  ROLE_MUST_BE_TEXT = "ROLE_MUST_BE_TEXT",
  ROLE_IS_INVALID = "ROLE_IS_INVALID",
}

export { ErrorCodes }
